services:
  
  order:
    depends_on:
      - order_db
    build: 
      context: .
      
    command: npm start
    ports:
      - 8085:8080
    environment:
      - DB_HOST=order_db
      - DB_USER=testadmin
      - DB_PASSWORD=testuser
      - DB_NAME=test_db
      - DB_PORT=5432
    
    volumes:
      - .:/app

    networks:
      - backend
  
  order_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=testadmin
      - POSTGRES_PASSWORD=testuser

    ports:
      - "5435:5432"
      
    networks:
      - backend
  
volumes:
  order_db:

networks:
  backend:
    external: true