version: '3.9'

services:
  
  app:
    depends_on:
      - db
    build: 
      context: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=testadmin
      - DB_PASSWORD=testuser
      - DB_NAME=test_db
      - DB_PORT=8081
    
    volumes:
      - .:/app
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=testadmin
      - POSTGRES_PASSWORD=testuser

volumes:
  db: