services:
  
  product:
    depends_on:
      - product_db
    build: 
      context: .
      
    command: npm start
    ports:
      - 8084:8080
    environment:
      - DB_HOST=product_db
      - DB_USER=testadmin
      - DB_PASSWORD=testuser
      - DB_NAME=test_db
      - DB_PORT=8092
    
    volumes:
      - .:/app

    networks:
      - backend
  
  product_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=testadmin
      - POSTGRES_PASSWORD=testuser

    ports:
      - "5434:5432"
      
    networks:
      - backend
  
volumes:
  product_db:

networks:
  backend:
    external: true