services:
  
  app:
    depends_on:
      - activity_db
    build: 
      context: .
    ports:
      - 8082:8080
    environment:
      - DB_HOST=db
      - DB_USER=testadmin
      - DB_PASSWORD=testuser
      - DB_NAME=test_db
      - DB_PORT=8092
    
    volumes:
      - .:/app

    networks:
      - backend
  
  activity_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=testadmin
      - POSTGRES_PASSWORD=testuser

    ports:
      - "8092:8082"

volumes:
  activity_db:

networks:
  backend:
    driver: bridge