services:
  
  activity:
    depends_on:
      - activity_db
    build: 
      context: .
      
    command: npm start
    ports:
      - 8082:8080
    environment:
      - DB_HOST=activity_db
      - DB_USER=testadmin
      - DB_PASSWORD=testuser
      - DB_NAME=test_db
      - DB_PORT=8092
    
    volumes:
      - .:/app

    networks:
      - backend
  
  activity_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=testadmin
      - POSTGRES_PASSWORD=testuser

    ports:
      - "5433:5432"
      
    networks:
      - backend
  
volumes:
  activity_db:

networks:
  backend:
    external: true